#  ⠀⢡⠀⠰⣶⣤⣦⣤⣔⣠⣄⣄⣐⣀⡀⠄⠀⠂⠄⡐⢠⢢⠀⣀⠲⡰⡄⠦⠔⠢⣥⠛⠲⢢⡆⣙⠲⠥⡍⠧⡍⠚⣠⡑⣈⣦⠗⣃⣩⡚⠸⡷⢺⢉⠶⡱⠰⡛⡬⠜⠮⠏⣝⣋⣍
#    ⠀⠄⠁⢸⣿⣿⡍⣽⢟⣿⣿⣿⣿⣿⠿⣿⣿⣿⣷⣶⣶⣶⣶⣶⣧⣤⣬⣥⣀⣀⣈⣐⣙⣲⢤⠩⠝⠒⣉⠱⢤⣗⢃⠰⢇⡒⠌⠄⠡⡑⣞⠔⡩⡍⠶⣒⣣⢰⠐⣜⠸⢽⣃⢭⢏
#    ⡀⢁⠂⢸⣯⠟⢜⣵⣿⣿⣿⠻⢿⣿⡷⢸⣿⣿⢣⣿⣿⣿⣿⣿⣿⡹⣿⡏⠻⠹⡛⣿⣿⣿⣿⡿⠿⣿⣿⣶⣶⣶⣶⣾⣶⣥⣬⣭⣤⣤⣙⣊⣲⡝⣐⣛⡈⠊⢓⡄⢆⡣⣌⣬⡵
#    ⢤⠈⠇⣿⢻⣴⡸⡀⠀⡀⠀⠀⠀⠀⠉⠁⢿⣿⠸⣛⡿⢿⣿⣿⣿⣇⣿⣇⣷⡇⢃⢿⣿⣿⣿⡇⡇⢹⣿⣿⣿⣿⣿⡿⣸⡿⣻⣯⢻⣿⣿⢛⣿⣿⣿⣿⣿⣿⣿⣿⣷⣶⣶⣿⣷
#    ⢈⡉⢤⣿⣾⣿⡇⣇⠀⢹⣿⣷⣤⣤⡀⠀⠘⡇⠀⠀⠙⢷⣎⡿⣿⣿⡘⡧⣿⣿⣦⢸⣿⣿⣿⡇⣿⡌⢿⣿⣿⣿⣿⣧⣿⢹⣿⣿⡎⣿⣿⢸⡸⣿⣿⣿⣿⣿⡘⣿⣿⢸⣿⣿⣿
#    ⠨⢌⢸⣇⣿⣿⡇⣿⣆⠈⣿⣿⣿⣿⡿⠇⢠⠀⢀⠀⠀⠀⠨⣵⣾⣿⣧⠃⣿⣿⣿⣎⢿⣿⣿⣿⢹⣏⡘⣿⣿⣿⡿⢸⣿⣾⣽⣿⣗⢻⣿⢸⣥⢿⣿⣿⣿⣿⢀⣿⢃⣿⣿⣿⣧
#    ⡐⢈⢸⣿⣿⣿⣷⢹⣿⡧⠙⣿⣿⣿⣷⡀⣜⡄⠘⠃⡠⠂⠀⠘⣿⣿⣿⣧⢹⣿⣿⣿⡜⡙⢿⣿⡎⣿⡖⢸⣿⣿⡇⣧⣽⣯⣭⣿⣿⡆⣿⡏⣿⣎⣿⣿⣿⣿⢨⠘⣼⣿⣿⣿⡷
#    ⢈⡥⣾⣿⣿⣿⣿⣇⢻⣶⣶⣴⣛⣿⣿⣷⣙⠷⣭⣽⣾⠆⣰⣷⣽⣿⣿⣿⣿⣿⣿⣿⣿⡜⢨⡻⣿⢸⣿⣆⢹⣿⢹⡿⠿⠿⠛⠛⠋⠘⠘⡇⢿⣿⡜⣿⣿⣿⠰⢱⣿⣿⣿⣿⠃
#    ⢋⠀⣿⢹⣿⣿⣿⡟⣎⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣾⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⠻⣮⡃⢻⣿⠅⠙⠀⢀⣀⣀⣀⠀⠀⠀⠀⠙⠀⠀⠈⠘⣿⣿⢀⣿⣿⣿⣿⣿⢏
#    ⣄⢻⣿⡇⠙⣿⣿⣧⢢⡀⠻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢿⣿⣿⣿⣷⣿⣿⣯⣶⣾⣿⣿⣿⣿⣿⣿⣄⠠⢸⠀⠀⣠⠀⠠⠀⣈⢧⣾⣿⣿⣿⣿⣟⠆
#    ⠲⣸⣇⡇⠀⠎⠻⣿⣧⠻⣶⣌⣻⣿⣿⣿⣿⣿⣿⣿⣿⣽⣿⡿⣿⣻⣿⣿⣿⣿⣿⣿⣿⣽⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣄⢤⣬⣄⡈⠁⡠⠃⠀⢁⣾⣿⣿⣿⣿⣿⡿⠢
#    ⡻⢿⣿⣥⣬⣿⠥⠬⣻⣷⣻⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣮⣟⣿⣿⣿⣯⣟⡿⣿⣿⣟⣯⣿⣿⣾⣝⣿⣿⣿⣿⣿⣿⣿⣿⣦⣉⣟⣚⡙⠛⠛⠛⡛⣤⢏⣾⣿⣿⣿⣿⣿⣿⡟⠥
#    ⣭⣀⡀⠈⣉⠉⡉⠙⠛⠛⠒⠛⠟⠛⠿⠿⠿⠿⢿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠿⢷⣾⣽⣻⣿⣽⣿⡿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡿⠷⡾⡿⣣⣿⣿⢿⣿⣿⣿⣿⣿⣟⡘
#    ⣚⠓⣦⠼⢢⠅⠮⡡⣞⡤⡘⢆⡐⢠⠐⢄⡀⢠⢀⢠⠀⠀⠀⢈⡠⡉⠉⠉⠉⠙⠛⠒⠚⠛⠟⠛⠾⠭⠽⠿⣿⣿⣿⣿⣿⣿⣿⠿⠫⣗⣩⣣⣞⣵⣿⣟⣳⣿⣿⣿⣿⢿⣼⢠⢃
#    ⢇⡽⢊⢮⢳⠝⠲⢣⠖⠶⠮⡘⠴⣠⣉⡐⢦⡄⣋⠈⠋⣒⡬⢐⠸⢡⣲⡉⢖⠀⠘⣄⢊⡰⢄⢠⠀⢤⠐⡠⢀⡀⠀⢈⡁⠉⠉⡉⠉⡉⠓⠒⠛⠛⠿⠻⠿⠿⠿⠿⣷⣛⣿⠅⢺
#    ⣱⠪⡽⢾⡫⢅⣏⠳⠌⡹⠩⡹⠄⢔⡈⢷⣃⠸⣮⠴⠾⠠⣉⠖⢣⣢⡁⠏⠡⡈⢅⡰⠉⡱⢁⠂⠩⢞⠈⡙⢂⠒⠡⠉⡙⣉⡄⠑⡌⣌⠁⡃⡀⢄⠠⡡⢤⢐⠠⢠⡀⣐⣤⠊⡰
#
#------------------------------------------------------------------------------------------
#                           C O N F I G      F I L E
#------------------------------------------------------------------------------------------
#                            This Plugin was Developed Lorenz
#                                 Name :  Purgatory
#-----------------------------------------------------------------------------------------
JAILSYSTEM:
  # The server of the player when connect after the ban
  server-jail: "Purgatorio"
  # Rendirect lobby when the player is unbanned.
  lobby-server: "hub-01"

# Don't change the Version
config_version: 1